
[package]
name = "ambient_gpu"
version = { workspace = true }
rust-version = { workspace = true }
edition = "2021"
description = "Ambient GPU functionality. Host-only."
license = "MIT OR Apache-2.0"
repository = "https://github.com/AmbientRun/Ambient"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ambient_sys = { path = "../sys" , version = "0.2.1" }
ambient_std = { path = "../std" , version = "0.2.1" }

aho-corasick = { workspace = true }
bytemuck = { workspace = true }
winit = { workspace = true }
wgpu = { workspace = true }
wgpu_core = { workspace = true }
wgpu_hal = { workspace = true }
glam = { workspace = true }
log = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
byteorder = { workspace = true }
image = { workspace = true }
itertools = { workspace = true }
ndarray = { workspace = true }
ordered-float = { workspace = true }
async-trait = { workspace = true }
futures = { workspace = true }
parking_lot = { workspace = true }
anyhow = { workspace = true }
tracing = { workspace = true }
directories = { workspace = true }
toml = { workspace = true }
serde = { workspace = true }
openxr = { workspace = true }

[features]
hotload-includes = ['ambient_std/hotload-includes']
